### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by aellwein** [benediktschmitt/py-jsonapi#6]
Installation from PyPi using pip fails with the following error message:
```
$ pip install py-jsonapi         
Collecting py-jsonapi
  Using cached py-jsonapi-0.3.2b0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-s88yf0l8/py-jsonapi/setup.py", line 29, in <module>
        import jsonapi
      File "/tmp/pip-build-s88yf0l8/py-jsonapi/jsonapi/__init__.py", line 26, in <module>
        from . import base
      File "/tmp/pip-build-s88yf0l8/py-jsonapi/jsonapi/base/__init__.py", line 47, in <module>
        from . import handler
      File "/tmp/pip-build-s88yf0l8/py-jsonapi/jsonapi/base/handler/__init__.py", line 37, in <module>
        from .base import BaseHandler
      File "/tmp/pip-build-s88yf0l8/py-jsonapi/jsonapi/base/handler/base.py", line 32, in <module>
        from ..errors import MethodNotAllowed
      File "/tmp/pip-build-s88yf0l8/py-jsonapi/jsonapi/base/errors.py", line 37, in <module>
        from cached_property import cached_property
    ImportError: No module named 'cached_property'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-s88yf0l8/py-jsonapi/

```

**Comment by benediktschmitt** [comment]
I fixed the typo in the *setup.py* file. The installation should now work.

**Comment by lukeorland** [comment]
Does a new version of this project need to be packaged and pushed to pypi.org? This problem still occurs with `pip install py-jsonapi`.
